### ISSUE TITLE
Request: deploy new version

### ISSUE THREAD

**Issue by remotejob** [riversun/chatux#14]
https://riversun.github.io/chatux/chatux.min.js

still chatux v1.0.11  It will be nice if you deploy new version chatux v1.1.0

Thanks.

**Comment by riversun** [comment]
Thanks for your comment.
The latest version is available.

https://riversun.github.io/chatux/chatux.min.js

**Comment by remotejob** [comment]
What about 'delay' option? Are you planning implement? If take in consideration it's included in botui

`botui.message.bot({
      delay: 5000,
      loading: true
    }).`

**Comment by riversun** [comment]
You can use the "delayMs" property like below,
 msg.push({
        type: 'text',
        value: 'Something',
        delayMs: 500
    });
